# WP-D run config: d_pma0_aug_lat16
model_name: rt_d_pma0_aug_lat16
data:
  preproc_type: PFPreProcessor
  val_split: 0.1
  pairwise: false
hyperparameters:
  num_epochs: 25
  early_stopping_patience: 5
  batch_size: 256
  mixed_prec: true
  lr: 0.001
  lr_min: 0.0
  lr_warmup: 0.05
  embed_size: 128
  num_heads: 8
  num_layers: 0
  latent_dim: 16
  proj_dim: 12
  linear_dim: null
  contrast_temp: 0.07
  contrastive_weight: 0.05
  contrastive_max: null
  contrastive_warmup: 0.05
  encoder_class: PMAEncoder
  use_degradation: true
